-- ws.`住民税` definition

CREATE TABLE `住民税` (
  `連番` int NOT NULL AUTO_INCREMENT,
  `ユーザID` varchar(200) DEFAULT NULL,
  `西暦` varchar(10) DEFAULT NULL,
  `年度` varchar(100) DEFAULT NULL,
  `受給者番号` varchar(100) DEFAULT NULL,
  `指定番号` varchar(100) DEFAULT NULL,
  `宛名番号` varchar(100) DEFAULT NULL,
  `所得_給与収入` int DEFAULT NULL,
  `所得_所得金額調整控除` int DEFAULT NULL,
  `所得_給与所得_所得金額調整控除後` int DEFAULT NULL,
  `所得_営業等所得` int DEFAULT NULL,
  `所得_その他の所得計` int DEFAULT NULL,
  `所得_総所得金額等` int DEFAULT NULL,
  `所得控除_雑損` int DEFAULT NULL,
  `所得控除_医療費` int DEFAULT NULL,
  `所得控除_社会保険料` int DEFAULT NULL,
  `所得控除_小規模企業共済` int DEFAULT NULL,
  `所得控除_生命保険料` int DEFAULT NULL,
  `所得控除_地震保険料` int DEFAULT NULL,
  `所得控除_基礎` int DEFAULT NULL,
  `所得控除_所得控除合計` int DEFAULT NULL,
  `課税標準_課税総所得` int DEFAULT NULL,
  `課税標準_山林所得` int DEFAULT NULL,
  `課税標準_分離短期譲渡` int DEFAULT NULL,
  `課税標準_分離長期譲渡` int DEFAULT NULL,
  `課税標準_株式等の譲渡` int DEFAULT NULL,
  `課税標準_上場株式等の配当等` int DEFAULT NULL,
  `課税標準_先物取引` int DEFAULT NULL,
  `税額_年税額` int DEFAULT NULL,
  `備考` varchar(200) DEFAULT NULL,
  `削除F` varchar(1) DEFAULT NULL,
  `登録日時` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `更新日時` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`連番`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

