-- ws.`資産管理` definition

CREATE TABLE `資産管理` (
  `連番` int NOT NULL AUTO_INCREMENT,
  `履歴番号` int DEFAULT NULL,
  `年月日` date DEFAULT NULL,
  `備考` varchar(200) DEFAULT NULL,
  `削除F` varchar(1) DEFAULT NULL,
  `登録日時` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `更新日時` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `ユーザID` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`連番`)
) ENGINE=InnoDB AUTO_INCREMENT=53 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;